from marshmallow import Schema, fields

class ProductUniqueSchema(Schema):
    id = fields.String()
    code = fields.String()
    name = fields.String()
    price = fields.Float()
    description = fields.String()
    weight = fields.String()
    establishmentID = fields.String()
    establishmentName = fields.String()
    establishmentPhone = fields.String()
    establishmentAddress = fields.String()
    establishmentNumber = fields.String()
    establishmentComplement = fields.String()
    establishmentNeighborhood = fields.String()
    establishmentCity = fields.String()
    establishmentState = fields.String()
    establishmentCountry = fields.String()
    establishmentLatitude = fields.String()
    establishmentLongitude = fields.String()
    establishmentOperatingHours = fields.String()
    establishmentFlgOpen = fields.String()
    photo = fields.String()